name: Auto Sync Core

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-core:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get latest release info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'MetaCubeX',
              repo: 'mihomo'
            });
            return response.data;
            
      - name: Download Linux AMD64
        run: |
          curl -L -o mihomo-linux-amd64-${{ steps.release.outputs.tag_name }}.gz \
          "https://github.com/MetaCubeX/mihomo/releases/download/${{ steps.release.outputs.tag_name }}/mihomo-linux-amd64-${{ steps.release.outputs.tag_name }}.gz"
          
      - name: Download Linux ARM Versions
        run: |
          # ARM64
          curl -L -o mihomo-linux-arm64-${{ steps.release.outputs.tag_name }}.gz \
          "https://github.com/MetaCubeX/mihomo/releases/download/${{ steps.release.outputs.tag_name }}/mihomo-linux-arm64-${{ steps.release.outputs.tag_name }}.gz"
          
          # ARMv7
          curl -L -o mihomo-linux-armv7-${{ steps.release.outputs.tag_name }}.gz \
          "https://github.com/MetaCubeX/mihomo/releases/download/${{ steps.release.outputs.tag_name }}/mihomo-linux-armv7-${{ steps.release.outputs.tag_name }}.gz"
          
          # ARMv5
          curl -L -o mihomo-linux-armv5-${{ steps.release.outputs.tag_name }}.gz \
          "https://github.com/MetaCubeX/mihomo/releases/download/${{ steps.release.outputs.tag_name }}/mihomo-linux-armv5-${{ steps.release.outputs.tag_name }}.gz"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add mihomo-linux-*.gz
          git commit -m "chore: sync core to ${{ steps.release.outputs.tag_name }}"
          git push